openapi: 3.0.0
info:
  title: Multi-Step Form Back
  description: Multi-Step Form Back
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
  # - url: https://galleria-arzk.onrender.com/api
  #   description: Web server
paths:
  # /paintings:
  #   get:
  #     summary: Get all paintings
  #     responses:
  #       "200":
  #         description: Successful response
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 type: string
  #       "400":
  #         description: Bad Request
  #         content:
  #           application/json:
  #             example:
  #               error: Bad request parameters
  #       "500":
  #         description: Internal Server Error
  #         content:
  #           application/json:
  #             example:
  #               error: Internal server error
