openapi: 3.0.0
info:
  title: Multi-Step Form Back
  description: Multi-Step Form Back
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
  - url: https://multi-step-form-ek9o.onrender.com/api
    description: Web server
paths:
  /personalinfo:
    post:
      tags:
        - Multi step form
      requestBody:
        description: post base
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required: true
                email:
                  type: string
                  required: true
                number:
                  type: number
                  required: true
                plan:
                  type: string
                onlineService:
                  type: string
                LargerStorage:
                  type: string
                CustomizableProfile:
                  type: string
      responses:
        "200":
          description: Multi step form data
